In [2]:
import example_robot_data as robex
import pinocchio as pin
import numpy as np
import rerun.blueprint as rrb
import rerun as rr

import sys
sys.path.append("../src")
from pinocchio_rerun import RerunVisualizer

solo = robex.load("solo12")
model = solo.model
visual_model = solo.visual_model
collision_model = solo.collision_model

rviz = RerunVisualizer(model, collision_model, visual_model, notebook_embed=True)
rviz.loadViewerModel()

print("Done loading model")

# rviz.addEllipsoid("obstacle", radii=np.array([0.1, 0.05, 0.02]), color=[255, 255, 0, 128])
# rviz.addBox("obstacle", size=[0.1, 0.05, 0.02], color=[255, 255, 0, 128])
# rviz.set_pose("obstacle", pose=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0])

# rviz.activateInertias()
rviz.display(pin.neutral(solo.model))

[2024-08-26T21:20:12Z INFO  re_sdk_comms::server] Hosting a SDK server over TCP at 0.0.0.0:9876. Connect with the Rerun logging SDK.
Error: winit EventLoopError: os error at /home/conda/feedstock_root/build_artifacts/rerun-sdk_1724135644780/_build_env/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/mod.rs:786: neither WAYLAND_DISPLAY nor WAYLAND_SOCKET nor DISPLAY is set.
[2024-08-26T21:20:12Z WARN  re_sdk_comms::buffered_client] Failed to send message after 3 attempts: Failed to connect to Rerun server at 127.0.0.1:9876: Connection refused (os error 111)
[2024-08-26T21:20:15Z WARN  re_sdk_comms::buffered_client] Dropping messages because tcp client has timed out.
[2024-08-26T21:20:15Z WARN  re_sdk_comms::buffered_client] Dropping messages because tcp client has timed out.
[2024-08-26T21:20:15Z WARN  re_sdk_comms::tcp_client] Tried to flush while TCP stream was still Pending. Data was possibly dropped.


Viewer()

/home/ldematteis/mambaforge/envs/Release/share/example-robot-data/robots/../../example-robot-data/robots/solo_description/meshes/stl/solo12/solo_12_base.stl
/home/ldematteis/mambaforge/envs/Release/share/example-robot-data/robots/../../example-robot-data/robots/solo_description/meshes/stl/solo12/solo12_hip_fe_fl.stl
/home/ldematteis/mambaforge/envs/Release/share/example-robot-data/robots/../../example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_upper_leg_left_side.stl
/home/ldematteis/mambaforge/envs/Release/share/example-robot-data/robots/../../example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_lower_leg_left_side.stl
/home/ldematteis/mambaforge/envs/Release/share/example-robot-data/robots/../../example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_foot.stl
/home/ldematteis/mambaforge/envs/Release/share/example-robot-data/robots/../../example-robot-data/robots/solo_description/meshes/stl/solo12/solo12_hip_fe_fr.stl
/home/ldematteis/mam

In [3]:
data = solo.model.createData()
dt = 1e-3
q = solo.q0
v = np.random.random(model.nv)*5
v[:6] = np.zeros(6)
for t in range(500):
    # a = pin.aba(solo.model, data, q, v, np.zeros(model.nv))
    # v += a * dt
    q = pin.integrate(model, q, v * dt)
    rviz.display(q)

FL_HFE
[[ 0.          1.         -0.        ]
 [ 0.11972949  0.         -0.99280655]
 [-0.99280655  0.         -0.11972949]]
FL_HFE
[[ 0.          1.         -0.        ]
 [ 0.11972949  0.         -0.99280655]
 [-0.99280655  0.         -0.11972949]]
FL_HFE
[[ 0.          1.         -0.        ]
 [ 0.11972949  0.         -0.99280655]
 [-0.99280655  0.         -0.11972949]]
FL_HFE
[[ 0.          1.         -0.        ]
 [ 0.11972949  0.         -0.99280655]
 [-0.99280655  0.         -0.11972949]]
FL_HFE
[[ 0.          1.         -0.        ]
 [ 0.11972949  0.         -0.99280655]
 [-0.99280655  0.         -0.11972949]]
FL_HFE
[[ 0.          1.         -0.        ]
 [ 0.11972949  0.         -0.99280655]
 [-0.99280655  0.         -0.11972949]]
FL_HFE
[[ 0.          1.         -0.        ]
 [ 0.11972949  0.         -0.99280655]
 [-0.99280655  0.         -0.11972949]]
FL_HFE
[[ 0.          1.         -0.        ]
 [ 0.11972949  0.         -0.99280655]
 [-0.99280655  0.         -0.11972949]]


In [5]:
q0 = solo.q0.copy()
q0[2] = 0.5
rviz.display(q0)

In [ ]:
solo.model.check(data)