In [2]:
import example_robot_data as robex
import pinocchio as pin
import numpy as np
import rerun.blueprint as rrb
import rerun as rr

from rerun_visualizer_draft import RerunVisualizer

solo = robex.load("solo12")
model = solo.model
visual_model = solo.visual_model
collision_model = solo.collision_model

rviz = RerunVisualizer(model, collision_model, visual_model)
rviz.loadViewerModel()

print("Done loading model")

# rviz.addEllipsoid("obstacle", radii=np.array([0.1, 0.05, 0.02]), color=[255, 255, 0, 128])
# rviz.addBox("obstacle", size=[0.1, 0.05, 0.02], color=[255, 255, 0, 128])
# rviz.set_pose("obstacle", pose=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0])

# rviz.activateInertias()
rviz.display(pin.neutral(solo.model))

[2024-08-26T11:16:33Z INFO  re_sdk::spawn] A process is already listening at this address. Assuming it's a Rerun Viewer. addr=0.0.0.0:9876


Done loading model
FL_HFE
[[ 0.          1.         -0.        ]
 [ 0.11972949  0.         -0.99280655]
 [-0.99280655  0.         -0.11972949]]


In [3]:
data = solo.model.createData()
dt = 1e-3
q = solo.q0
v = np.random.random(model.nv)*5
v[:6] = np.zeros(6)
for t in range(500):
    # a = pin.aba(solo.model, data, q, v, np.zeros(model.nv))
    # v += a * dt
    q = pin.integrate(model, q, v * dt)
    rviz.display(q)

FL_HFE
[[ 0.          1.         -0.        ]
 [ 0.11972949  0.         -0.99280655]
 [-0.99280655  0.         -0.11972949]]
FL_HFE
[[ 0.          1.         -0.        ]
 [ 0.11972949  0.         -0.99280655]
 [-0.99280655  0.         -0.11972949]]
FL_HFE
[[ 0.          1.         -0.        ]
 [ 0.11972949  0.         -0.99280655]
 [-0.99280655  0.         -0.11972949]]
FL_HFE
[[ 0.          1.         -0.        ]
 [ 0.11972949  0.         -0.99280655]
 [-0.99280655  0.         -0.11972949]]
FL_HFE
[[ 0.          1.         -0.        ]
 [ 0.11972949  0.         -0.99280655]
 [-0.99280655  0.         -0.11972949]]
FL_HFE
[[ 0.          1.         -0.        ]
 [ 0.11972949  0.         -0.99280655]
 [-0.99280655  0.         -0.11972949]]
FL_HFE
[[ 0.          1.         -0.        ]
 [ 0.11972949  0.         -0.99280655]
 [-0.99280655  0.         -0.11972949]]
FL_HFE
[[ 0.          1.         -0.        ]
 [ 0.11972949  0.         -0.99280655]
 [-0.99280655  0.         -0.11972949]]


In [5]:
q0 = solo.q0.copy()
q0[2] = 0.5
rviz.display(q0)

In [ ]:
solo.model.check(data)